import json
import os

with open('picht360_prueba.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Modificar Celda 5 (Clustering)
nb['cells'][14]['source'] = [
    "from sklearn.cluster import KMeans\n",
    "from sklearn.preprocessing import normalize\n",
    "import numpy as np\n",
    "\n",
    "palabras_validas = [p for p in vocabulario if p in stats]\n",
    "\n",
    "if len(palabras_validas) > 0:\n",
    "    vectores_promedio = np.array([stats[p]['centroide'] for p in palabras_validas])\n",
    "    \n",
    "    # LA SOLUCIÓN MAGICA: Restar la media global (Centrar vectores)\n",
    "    media_global = np.mean(vectores_promedio, axis=0)\n",
    "    vectores_centrados = vectores_promedio - media_global\n",
    "    \n",
    "    # Normalizamos post-centrado\n",
    "    vectores_norm = normalize(vectores_centrados)\n",
    "\n",
    "    # Usamos KMeans con 8 temas forzados\n",
    "    num_clusters = 8\n",
    "    clusterer = KMeans(n_clusters=num_clusters, random_state=42, n_init='auto')\n",
    "    etiquetas = clusterer.fit_predict(vectores_norm)\n",
    "\n",
    "    clusters = {}\n",
    "    for palabra, etiqueta in zip(palabras_validas, etiquetas):\n",
    "        if etiqueta not in clusters:\n",
    "            clusters[etiqueta] = []\n",
    "        clusters[etiqueta].append(palabra)\n",
    "        \n",
    "    print(f'Se forzaron y encontraron {len(clusters)} clusters semánticos usando Vectores Centrados.')\n",
    "else:\n",
    "    print('No hay palabras para clusterizar.')\n"
]

# Modificar Celda 6 (Logica y Dataframe)
nb['cells'][16]['source'] = [
    "from sklearn.metrics.pairwise import cosine_distances, cosine_similarity\n",
    "import anthropic\n",
    "import pandas as pd\n",
    "\n",
    "UMBRAL_SIGNIFICANTE_VACIO = 0.5\n",
    "UMBRAL_CADENAS = 0.85 # Subimos exigencia para evitar que todas entren\n",
    "\n",
    "def identificar_significante_vacio(cluster_palabras, stats):\n",
    "    if not cluster_palabras: return None\n",
    "    scores = []\n",
    "    # Para el cálculo interno, usamos los vectores norm normalizados\n",
    "    vect_temp = np.array([stats[p]['centroide'] for p in cluster_palabras])\n",
    "    vect_cent = vect_temp - np.mean(vect_temp, axis=0)\n",
    "    if len(vect_cent) < 2: return cluster_palabras[0]\n",
    "    vectores_cluster = normalize(vect_cent)\n",
    "    \n",
    "    for i, palabra in enumerate(cluster_palabras):\n",
    "        dispersion = stats[palabra]['dispersion']\n",
    "        dist = cosine_distances(vectores_cluster[i].reshape(1, -1), vectores_cluster)\n",
    "        centralidad = 1 - float(np.mean(dist))\n",
    "        score = 0.3 * dispersion + 0.7 * centralidad\n",
    "        scores.append((palabra, score))\n",
    "    scores.sort(key=lambda x: x[1], reverse=True)\n",
    "    if scores and scores[0][1] > UMBRAL_SIGNIFICANTE_VACIO:\n",
    "        return scores[0][0]\n",
    "    return None\n",
    "\n",
    "def similitud_segundo_orden(idx_a, idx_b, todos_vectores):\n",
    "    perfil_a = cosine_similarity(todos_vectores[idx_a].reshape(1, -1), todos_vectores)[0]\n",
    "    perfil_b = cosine_similarity(todos_vectores[idx_b].reshape(1, -1), todos_vectores)[0]\n",
    "    return cosine_similarity(perfil_a.reshape(1, -1), perfil_b.reshape(1, -1))[0][0]\n",
    "\n",
    "def identificar_cadenas(cluster_palabras, palabras_validas, todos_vectores_norm, significante_vacio, umbral):\n",
    "    if significante_vacio:\n",
    "        scores = []\n",
    "        idx_sv = palabras_validas.index(significante_vacio)\n",
    "        for palabra in cluster_palabras:\n",
    "            if palabra == significante_vacio:\n",
    "                continue\n",
    "            idx_p = palabras_validas.index(palabra)\n",
    "            sim = similitud_segundo_orden(idx_sv, idx_p, todos_vectores_norm)\n",
    "            scores.append((palabra, sim))\n",
    "        candidatas = [p for p, s in scores if s > umbral]\n",
    "        if candidatas:\n",
    "            return [[significante_vacio] + candidatas]\n",
    "    return []\n",
    "\n",
    "import anthropic\n",
    "client = anthropic.Anthropic()\n",
    "def detectar_frame(c_id, palabras, sv, cadenas):\n",
    "    prompt = f\"\"\"Eres un experto en análisis del discurso político.\\nAnaliza este campo semántico: {palabras}\\nSignificante Vacío: {sv}\\nCadenas: {cadenas}\\n\\nBusca anomalías de asociación. Si el candidato junta elementos que lingüísticamente no van juntos, ¿qué Frame está construyendo? Responde solo en JSON: {{\\\"frame\\\": \\\"NOMBRE-FRAME\\\", \\\"descripcion\\\": \\\"...\\\"}}\"\"\"\n",
    "    try:\n",
    "        msg = client.messages.create(model='claude-3-haiku-20240307', max_tokens=300, messages=[{\"role\": \"user\", \"content\": prompt}])\n",
    "        return msg.content[0].text\n",
    "    except Exception as e:\n",
    "        return \"Error API: \" + str(e)\n",
    "\n",
    "resultados_clusters = {}\n",
    "if len(palabras_validas) > 0:\n",
    "    for c_id, palabras in clusters.items():\n",
    "        sv = identificar_significante_vacio(palabras, stats)\n",
    "        cadenas = identificar_cadenas(palabras, palabras_validas, vectores_norm, sv, UMBRAL_CADENAS)\n",
    "        \n",
    "        # Descomenta abajo sólo si ya pusiste la API\n",
    "        frame_info = \"Llamada a IA comentada para probar clustering primero.\"\n",
    "        # frame_info = detectar_frame(c_id, palabras[:15], sv, cadenas)\n",
    "        \n",
    "        resultados_clusters[c_id] = {\n",
    "            'tamaño_cluster': len(palabras),\n",
    "            'palabras_clave': \", \".join(palabras[:10]),\n",
    "            'significante_vacio': sv if sv else \"Ninguno\",\n",
    "            'cadenas_equivalencia': \" = \".join(cadenas[0][:5]) + \"...\" if cadenas else \"Ninguna\",\n",
    "            'frame_detectado': frame_info\n",
    "        }\n",
    "\n",
    "if resultados_clusters:\n",
    "    df_resultados = pd.DataFrame.from_dict(resultados_clusters, orient='index').sort_values(by='tamaño_cluster', ascending=False)\n",
    "    display(df_resultados)\n"
]

# Modificar Celda 7 (Plotly 3D)
nb['cells'][18]['source'] = [
    "import plotly.express as px\n",
    "from sklearn.manifold import TSNE\n",
    "\n",
    "categorias_teoricas = {}\n",
    "for c_id, res in resultados_clusters.items():\n",
    "    sv = res.get('significante_vacio')\n",
    "    if sv != \"Ninguno\": categorias_teoricas[sv] = 'Significante Vacío'\n",
    "    cads = res.get('cadenas_equivalencia')\n",
    "    if cads and cads != \"Ninguna\":\n",
    "        for p in cads.replace(\" ...\",\"\").split(\" = \"):\n",
    "            if p not in categorias_teoricas: categorias_teoricas[p] = 'Cadena de Equiv'\n",
    "\n",
    "tsne_3d = TSNE(n_components=3, random_state=42, perplexity=min(30, len(vectores_norm) - 1))\n",
    "# Es CRÍTICO usar los vectores centrados (vectores_norm) para que TSNE explote la esfera\n",
    "coords_3d = tsne_3d.fit_transform(vectores_norm)\n",
    "\n",
    "datos_grafica = []\n",
    "for i, palabra in enumerate(palabras_validas):\n",
    "    cluster_num = \"Ruido\"\n",
    "    for c_id, p_list in clusters.items():\n",
    "        if palabra in p_list: cluster_num = f\"Cluster {c_id}\"; break\n",
    "    \n",
    "    cat = categorias_teoricas.get(palabra, \"Vocabulario Normal\")\n",
    "    \n",
    "    datos_grafica.append({\"Palabra\": palabra, \"X\": coords_3d[i,0], \"Y\": coords_3d[i,1], \"Z\": coords_3d[i,2], \"Campo Semántico\": cluster_num, \"Rol\": cat})\n",
    "\n",
    "df_grafica = pd.DataFrame(datos_grafica)\n",
    "fig = px.scatter_3d(df_grafica, x='X', y='Y', z='Z', color='Campo Semántico', symbol='Rol', text='Palabra', hover_data=['Rol'], opacity=0.8, title=\"Mapa Semántico 3D Centrado\")\n",
    "fig.update_traces(textposition='top center', textfont_size=9, marker=dict(size=6))\n",
    "fig.update_layout(height=800, width=1000)\n",
    "fig.show()\n"
]

with open('picht360_prueba.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2, ensure_ascii=False)
